schemaVersion: 2.3.0
metadata:
  generateName: multicluster-redirector
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      memoryLimit: 6G
      memoryRequest: 512Mi
      cpuRequest: 1000m
      cpuLimit: 4000m
      mountSources: true
commands:
  - id: compile
    exec:
      label: Compile project
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: ./mvnw compile
      group:
        kind: build
        isDefault: true
  - id: dev
    exec:
      label: Run in dev mode
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: ./mvnw compile quarkus:dev
      group:
        kind: run
        isDefault: true
  - id: test
    exec:
      label: Run tests
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: ./mvnw test
      group:
        kind: test
        isDefault: true
  - id: package
    exec:
      label: Package application
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: ./mvnw package
      group:
        kind: build
