schemaVersion: 2.3.0
metadata:
  generateName: multicluster-redirector
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      memoryLimit: 6G
      memoryRequest: 512Mi
      cpuRequest: 1000m
      cpuLimit: 4000m
      mountSources: true
