quarkus.container-image.builder=docker
quarkus.container-image.registry=quay.io
quarkus.container-image.name=redhat-developer/crw-multicluster-redirector
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21
developer.sandbox.registration-service.url=https://registration-service-toolchain-host-operator.apps.sandbox.x8i5.p1.openshiftapps.com
%dev.developer.sandbox.registration-service.url=https://registration-service-ibuziuk-host-operator.apps-crc.testing
