####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/crw-multicluster-redirector .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/crw-multicluster-redirector
#
# The quarkus micro image is based on UBI 9 Micro and contains only the libraries
# required to run a native executable, minimizing the container attack surface.
###
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
COPY --chmod=0755 target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
