name: build

on:
  push:
    branches:
      - "master"

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn clean install
